title: "D-Minus"
description: ""
baseurl: /
url: http://www.dminusmusic.com
timezone: Europe/London
image: /images/banner.png
locale: en_AU
author: Adam Bouqdib
markdown: kramdown
facebook: dminusOz
twitter: dminusOz
youtube: dminus5
instagram: dminusofficial
reverbnation: dminusmusic
v: 38
